# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  service:
    serializer: fos_rest.serializer.symfony
  body_converter:
    enabled: true
  param_fetcher_listener:  true
  #    allowed_methods_listener:  true
  #    routing_loader: true
  view:
    formats: { json: true, xml: false, rss: false }
    view_response_listener: true
  serializer:
    serialize_null: true
  #        view_response_listener:  true
  #    exception:
  #        codes:
  #            App\Exception\MyException: 403
  #        messages:
  #            App\Exception\MyException: Forbidden area.
  format_listener:
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: 'json' }
